# -*- coding: utf-8 -*-
"""provão

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kbu6Co8NepUbe6e3Q7Oqc9zEXGFIkjOC
"""

### Questão 1) Importe o arquivo CSV e crie um DataFrame chamado `df`.

import pandas as pd

caminho = "/content/avaliacao_empresa.csv"
dados = pd.read_csv(caminho)

df

### Questão 2) Mostre os **5 primeiros** elementos do DataFrame.
import pandas as pd

caminho = "/content/avaliacao_empresa.csv"

dados = pd.read_csv(caminho)
df.head(5)

### Questão 3) Exiba as **informações gerais** do DataFrame (tipos de dados e nulos).
import pandas as pd

caminho = "/content/avaliacao_empresa.csv"


df = pd.read_csv(caminho)
df.info()

### Questão 4) Mostre o **formato (linhas, colunas)** e a **lista de colunas** do DataFrame.

import pandas as pd

caminho = "/content/avaliacao_empresa.csv"

dados = pd.read_csv(caminho)
df = pd.DataFrame(dados)
df.columns,df.shape

### Questão 5) Exiba as **estatísticas descritivas** das colunas numéricas (média, min, max, etc.).
import pandas as pd

caminho = "/content/avaliacao_empresa.csv"

dados = pd.read_csv(caminho)
df = pd.DataFrame(dados)
df.describe()

### Questão 6) Selecione apenas as colunas `nome` e `departamento` e mostre as **5 primeiras** linhas.


import pandas as pd

caminho = "/content/avaliacao_empresa.csv"

dados = pd.read_csv(caminho)
df = pd.DataFrame(dados)
df[['nome','departamento']].head(5)

### Questão 7) Filtre os registros do **turno 'Noite'** e **conte** quantos registros existem.
import pandas as pd

caminho = "/content/avaliacao_empresa.csv"

dados = pd.read_csv(caminho)
df = pd.DataFrame(dados)
df[df['turno']=='Noite'].value_counts()

### Questão 8) O código abaixo converte as datas de texto para data e em seguida cria uma coluna mês para os dados.

import pandas as pd

caminho = "/content/avaliacao_empresa.csv"
df = pd.DataFrame(dados)
dados = pd.read_csv(caminho)

df['data']=pd.to_datetime(df['data'],errors='coerce')
df['mes']=df['data'].dt.to_period('M').astype(str)
df[['data','mes']].head(5)

### Questão 9) O código abaixo agrupa e soma os valores por mes no DataFrame fat.
import pandas as pd

caminho = "/content/avaliacao_empresa.csv"

dados = pd.read_csv(caminho)
df = pd.DataFrame(dados)


df['data']=pd.to_datetime(df['data'],errors='coerce')
df['mes']=df['data'].dt.to_period('M').astype(str)
df[['data','mes',]].head(3)
df.groupby('mes',as_index=False)['faturamento'].max().head(3)

### Questão 10) Calcule a **média de salário por departamento** e mostre em **ordem decrescente**.

import pandas as pd

caminho = "/content/avaliacao_empresa.csv"
df = pd.DataFrame(dados)
dados = pd.read_csv(caminho)


df.groupby('departamento',as_index=False)['salario'].mean().sort_values('salario',ascending=True)



